INSERT INTO books(title, author)
values ('Superhuman by habit', 'Tynan'),
       ('Wie man Freunde gewinnt', 'Dale Carnegie'),
       ('Immun', 'Philip Dettmer'),
       ('Atomic Habits', 'James Clear'),
       ('The Linux Command Line, 2nd Edition', 'William Shotts'),
       ('Das einzige Buch, das Du ueber Finanzen lesen solltest', 'Thomas Kehl'),
       ('The Boy, The Mole, The Fox and The Horse', 'Charlie Mackesy'),
       ('Son of a Liche', 'Zachary Pike'),
       ('Orconomics', 'Zachary Pike'),
       ('Ready Player One', 'Ernest Cline'),
       ('Ready Player Two', 'Dale Carnegie'),
       ('Creativity Inc.', 'Edwin Catmull'),
       ('Effective Java, Third Edition', 'Bloch'),
       ('48 Laws of Power', 'Robert Greene'),
       ('Talent is Overrated', 'Daniel Pink'),
       ('Cashflow Quadrant', 'Robert Kiyosaki'),
       ('Are you smart enough to work for Google', 'William Poundstone'),
       ('Bock auf echtes Deutsch?', 'Angelika Bohn'),
       ('The Midnight Library', 'Matt Haig'),
       ('Miteinander reden', 'von Thun'),
       ('Mastering Bitcoin', 'Andreas M. Antonopoulos'),
       ('Mastering Ethereum', 'Andreas M. Antonopoulos');